version: '3.8'

services:
  # The Message Broker
  nats:
    image: nats:alpine
    ports:
      - "4222:4222" # Client port for your Go services to connect
      - "8222:8222" # HTTP management port
    command: ["-js"] # This flag is crucial: it enables JetStream

  # The Relational Database
  postgres:
    image: postgres:15-alpine
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=fintech_user
      - POSTGRES_PASSWORD=supersecretpassword
      - POSTGRES_DB=trading_simulator
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: # This ensures your database data isn't lost when you stop the container